<?php

/**
 * This is the model base class for the table "multi_language".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MultiLanguage".
 *
 * Columns in table "multi_language" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $noti_key
 * @property string $noti_eng
 * @property string $noti_other
 *
 */
abstract class BaseMultiLanguage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'multi_language';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notification|Notifications', $n);
	}

	public static function representingColumn() {
		return 'noti_key';
	}

	public function rules() {
		return array(
	    	array('noti_key,noti_eng', 'required'),
			array('noti_key', 'length', 'max'=>100),
			array('noti_eng, noti_other', 'safe'),
			array('noti_key, noti_eng, noti_other', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, noti_key, noti_eng, noti_other', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'noti_key' => Yii::t('app', 'Notification Key'),
			'noti_eng' => Yii::t('app', 'Notification English'),
			'noti_other' => Yii::t('app', 'Notification Other'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('noti_key', $this->noti_key, true);
		$criteria->compare('noti_eng', $this->noti_eng, true);
		$criteria->compare('noti_other', $this->noti_other, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}