<?php

/**
 * This is the model base class for the table "feed_detail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeedDetail".
 *
 * Columns in table "feed_detail" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $author_id
 * @property string $feed_title
 * @property string $feed_content
 * @property string $feed_image
 * @property string $feed_video
 * @property integer $status
 * @property integer $feed_privacy
 * @property integer $feed_share
 * @property string $created_at
 *
 */
abstract class BaseFeedDetail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'feed_detail';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeedDetail|FeedDetails', $n);
	}

	public static function representingColumn() {
		return 'feed_title';
	}

	public function rules() {
		return array(
			array('author_id, feed_title, feed_content, feed_image, feed_video, status, created_at', 'required'),
			array('author_id, status, feed_privacy, feed_share', 'numerical', 'integerOnly'=>true),
			array('feed_title, feed_content, feed_image', 'length', 'max'=>255),
			array('feed_privacy, feed_share', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, author_id, feed_title, feed_content, feed_image, feed_video, status, feed_privacy, feed_share, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'author_id' => Yii::t('app', 'Author'),
			'feed_title' => Yii::t('app', 'Feed Title'),
			'feed_content' => Yii::t('app', 'Feed Content'),
			'feed_image' => Yii::t('app', 'Feed Image'),
			'feed_video' => Yii::t('app', 'Feed Video'),
			'status' => Yii::t('app', 'Status'),
			'feed_privacy' => Yii::t('app', 'Feed Privacy'),
			'feed_share' => Yii::t('app', 'Feed Share'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('author_id', $this->author_id);
		$criteria->compare('feed_title', $this->feed_title, true);
		$criteria->compare('feed_content', $this->feed_content, true);
		$criteria->compare('feed_image', $this->feed_image, true);
		$criteria->compare('feed_video', $this->feed_video, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('feed_privacy', $this->feed_privacy);
		$criteria->compare('feed_share', $this->feed_share);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}