<?php

/**
 * This is the model base class for the table "promotion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Promotion".
 *
 * Columns in table "promotion" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $promotion_id
 * @property integer $user_id
 * @property string $promotion_title
 * @property string $promotion_description
 * @property integer $category_id
 * @property integer $subcategory_id
 * @property double $rate
 * @property integer $work_type
 * @property integer $pay_by
 * @property string $promotion_datetime
 * @property string $promotion_expiredatetime
 *
 */
abstract class BasePromotion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'promotion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Promotion|Promotions', $n);
	}

	public static function representingColumn() {
		return 'promotion_title';
	}

	public function rules() {
		return array(
			array('user_id, promotion_title, promotion_description, category_id, subcategory_id, rate, work_type, pay_by, promotion_datetime, promotion_expiredatetime', 'required'),
			array('user_id, category_id, subcategory_id, work_type, pay_by', 'numerical', 'integerOnly'=>true),
			array('rate', 'numerical'),
			array('promotion_title', 'length', 'max'=>200),
			array('promotion_id, user_id, promotion_title, promotion_description, category_id, subcategory_id, rate, work_type, pay_by, promotion_datetime, promotion_expiredatetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'promotion_id' => Yii::t('app', 'Promotion'),
			'user_id' => Yii::t('app', 'User'),
			'promotion_title' => Yii::t('app', 'Promotion Title'),
			'promotion_description' => Yii::t('app', 'Promotion Description'),
			'category_id' => Yii::t('app', 'Category'),
			'subcategory_id' => Yii::t('app', 'Subcategory'),
			'rate' => Yii::t('app', 'Rate'),
			'work_type' => Yii::t('app', 'Work Type'),
			'pay_by' => Yii::t('app', 'Pay By'),
			'promotion_datetime' => Yii::t('app', 'Promotion Datetime'),
			'promotion_expiredatetime' => Yii::t('app', 'Promotion Expiredatetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('promotion_id', $this->promotion_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('promotion_title', $this->promotion_title, true);
		$criteria->compare('promotion_description', $this->promotion_description, true);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('subcategory_id', $this->subcategory_id);
		$criteria->compare('rate', $this->rate);
		$criteria->compare('work_type', $this->work_type);
		$criteria->compare('pay_by', $this->pay_by);
		$criteria->compare('promotion_datetime', $this->promotion_datetime, true);
		$criteria->compare('promotion_expiredatetime', $this->promotion_expiredatetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}