<?php

/**
 * This is the model base class for the table "user_review".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserReview".
 *
 * Columns in table "user_review" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $review_by
 * @property integer $pb_id
 * @property integer $review_count
 * @property string $review
 * @property string $review_date
 *
 */
abstract class BaseUserReview extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_review';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserReview|UserReviews', $n);
	}

	public static function representingColumn() {
		return 'review';
	}

	public function rules() {
		return array(
			array('user_id, review_by, pb_id, review_count, review, review_date', 'required'),
			array('user_id, review_by, pb_id, review_count', 'numerical', 'integerOnly'=>true),
			array('id, user_id, review_by, pb_id, review_count, review, review_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'review_by' => Yii::t('app', 'Review By'),
			'pb_id' => Yii::t('app', 'Pb'),
			'review_count' => Yii::t('app', 'Review Count'),
			'review' => Yii::t('app', 'Review'),
			'review_date' => Yii::t('app', 'Review Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('review_by', $this->review_by);
		$criteria->compare('pb_id', $this->pb_id);
		$criteria->compare('review_count', $this->review_count);
		$criteria->compare('review', $this->review, true);
		$criteria->compare('review_date', $this->review_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}