<?php

/**
 * This is the model base class for the table "promotion_users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PromotionUsers".
 *
 * Columns in table "promotion_users" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $promotion_users_id
 * @property integer $promotion_id
 * @property integer $user_id
 * @property string $created_at
 *
 */
abstract class BasePromotionUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'promotion_users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PromotionUsers|PromotionUsers', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('promotion_id, user_id, created_at', 'required'),
			array('promotion_id, user_id', 'numerical', 'integerOnly'=>true),
			array('promotion_users_id, promotion_id, user_id, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'promotion_users_id' => Yii::t('app', 'Promotion Users'),
			'promotion_id' => Yii::t('app', 'Promotion'),
			'user_id' => Yii::t('app', 'User'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('promotion_users_id', $this->promotion_users_id);
		$criteria->compare('promotion_id', $this->promotion_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}