<?php

/**
 * This is the model base class for the table "postlike".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Postlike".
 *
 * Columns in table "postlike" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $postlike_id
 * @property integer $post_id
 * @property integer $user_id
 * @property string $created_at
 *
 */
abstract class BasePostlike extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'postlike';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Postlike|Postlikes', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('post_id, user_id, created_at', 'required'),
			array('post_id, user_id', 'numerical', 'integerOnly'=>true),
			array('postlike_id, post_id, user_id, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'postlike_id' => Yii::t('app', 'Postlike'),
			'post_id' => Yii::t('app', 'Post'),
			'user_id' => Yii::t('app', 'User'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('postlike_id', $this->postlike_id);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}