<?php

/**
 * This is the model base class for the table "post_bid".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PostBid".
 *
 * Columns in table "post_bid" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $pb_id
 * @property integer $user_id
 * @property integer $offer_by
 * @property integer $post_id
 * @property string $job_title
 * @property string $job_description
 * @property integer $category_id
 * @property integer $subcategory_id
 * @property integer $work_type
 * @property integer $exp_level
 * @property integer $commitment
 * @property integer $bid_by
 * @property integer $how_long
 * @property integer $pay_by
 * @property double $rate
 * @property double $approved_hour
 * @property string $description
 * @property string $attachments
 * @property string $skill
 * @property string $selected_skill
 * @property string $preferred_datetime
 * @property string $address
 * @property double $latitude
 * @property double $longtitude
 * @property string $notes
 * @property string $client_attachments
 * @property string $response_datetime
 * @property string $signature
 * @property integer $is_agree
 * @property integer $status
 * @property string $bid_datetime
 * @property string $offer_datetime
 * @property integer $offer_status
 * @property double $total_amount
 * @property string $payment_info
 * @property string $payment_datetime
 * @property integer $review_by_client
 * @property integer $review_by_user
 * @property string $temp_review
 * @property integer $is_temp_payment
 * @property string $temp_payment_request_datetime
 * @property integer $notification_id
 * @property integer $payment_type
 * @property integer $payment_request
 * @property string $payment_request_datetime
 * @property string $cancel_datetime
 * @property integer $is_offer
 *
 */
abstract class BasePostBid extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post_bid';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PostBid|PostBids', $n);
	}

	public static function representingColumn() {
		return 'job_title';
	}

	public function rules() {
		return array(
			array('user_id, offer_by, post_id, job_title, job_description, category_id, subcategory_id, work_type, exp_level, commitment, bid_by, how_long, pay_by, rate, approved_hour, description, attachments, skill, selected_skill, preferred_datetime, address, latitude, longtitude, notes, client_attachments, response_datetime, signature, is_agree, status, bid_datetime, offer_datetime, total_amount, payment_info, payment_datetime, temp_review, temp_payment_request_datetime, notification_id, payment_type', 'required'),
			array('user_id, offer_by, post_id, category_id, subcategory_id, work_type, exp_level, commitment, bid_by, how_long, pay_by, is_agree, status, offer_status, review_by_client, review_by_user, is_temp_payment, notification_id, payment_type, payment_request, is_offer', 'numerical', 'integerOnly'=>true),
			array('rate, approved_hour, latitude, longtitude, total_amount', 'numerical'),
			array('signature', 'length', 'max'=>200),
			array('payment_request_datetime, cancel_datetime', 'safe'),
			array('offer_status, review_by_client, review_by_user, is_temp_payment, payment_request, payment_request_datetime, cancel_datetime, is_offer', 'default', 'setOnEmpty' => true, 'value' => null),
			array('pb_id, user_id, offer_by, post_id, job_title, job_description, category_id, subcategory_id, work_type, exp_level, commitment, bid_by, how_long, pay_by, rate, approved_hour, description, attachments, skill, selected_skill, preferred_datetime, address, latitude, longtitude, notes, client_attachments, response_datetime, signature, is_agree, status, bid_datetime, offer_datetime, offer_status, total_amount, payment_info, payment_datetime, review_by_client, review_by_user, temp_review, is_temp_payment, temp_payment_request_datetime, notification_id, payment_type, payment_request, payment_request_datetime, cancel_datetime, is_offer', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'pb_id' => Yii::t('app', 'Pb'),
			'user_id' => Yii::t('app', 'User'),
			'offer_by' => Yii::t('app', 'Offer By'),
			'post_id' => Yii::t('app', 'Post'),
			'job_title' => Yii::t('app', 'Job Title'),
			'job_description' => Yii::t('app', 'Job Description'),
			'category_id' => Yii::t('app', 'Category'),
			'subcategory_id' => Yii::t('app', 'Subcategory'),
			'work_type' => Yii::t('app', 'Work Type'),
			'exp_level' => Yii::t('app', 'Exp Level'),
			'commitment' => Yii::t('app', 'Commitment'),
			'bid_by' => Yii::t('app', 'Bid By'),
			'how_long' => Yii::t('app', 'How Long'),
			'pay_by' => Yii::t('app', 'Pay By'),
			'rate' => Yii::t('app', 'Rate'),
			'approved_hour' => Yii::t('app', 'Approved Hour'),
			'description' => Yii::t('app', 'Description'),
			'attachments' => Yii::t('app', 'Attachments'),
			'skill' => Yii::t('app', 'Skill'),
			'selected_skill' => Yii::t('app', 'Selected Skill'),
			'preferred_datetime' => Yii::t('app', 'Preferred Datetime'),
			'address' => Yii::t('app', 'Address'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longtitude' => Yii::t('app', 'Longtitude'),
			'notes' => Yii::t('app', 'Notes'),
			'client_attachments' => Yii::t('app', 'Client Attachments'),
			'response_datetime' => Yii::t('app', 'Response Datetime'),
			'signature' => Yii::t('app', 'Signature'),
			'is_agree' => Yii::t('app', 'Is Agree'),
			'status' => Yii::t('app', 'Status'),
			'bid_datetime' => Yii::t('app', 'Bid Datetime'),
			'offer_datetime' => Yii::t('app', 'Offer Datetime'),
			'offer_status' => Yii::t('app', 'Offer Status'),
			'total_amount' => Yii::t('app', 'Total Amount'),
			'payment_info' => Yii::t('app', 'Payment Info'),
			'payment_datetime' => Yii::t('app', 'Payment Datetime'),
			'review_by_client' => Yii::t('app', 'Review By Client'),
			'review_by_user' => Yii::t('app', 'Review By User'),
			'temp_review' => Yii::t('app', 'Temp Review'),
			'is_temp_payment' => Yii::t('app', 'Is Temp Payment'),
			'temp_payment_request_datetime' => Yii::t('app', 'Temp Payment Request Datetime'),
			'notification_id' => Yii::t('app', 'Notification'),
			'payment_type' => Yii::t('app', 'Payment Type'),
			'payment_request' => Yii::t('app', 'Payment Request'),
			'payment_request_datetime' => Yii::t('app', 'Payment Request Datetime'),
			'cancel_datetime' => Yii::t('app', 'Cancel Datetime'),
			'is_offer' => Yii::t('app', 'Is Offer'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('pb_id', $this->pb_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('offer_by', $this->offer_by);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('job_title', $this->job_title, true);
		$criteria->compare('job_description', $this->job_description, true);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('subcategory_id', $this->subcategory_id);
		$criteria->compare('work_type', $this->work_type);
		$criteria->compare('exp_level', $this->exp_level);
		$criteria->compare('commitment', $this->commitment);
		$criteria->compare('bid_by', $this->bid_by);
		$criteria->compare('how_long', $this->how_long);
		$criteria->compare('pay_by', $this->pay_by);
		$criteria->compare('rate', $this->rate);
		$criteria->compare('approved_hour', $this->approved_hour);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('attachments', $this->attachments, true);
		$criteria->compare('skill', $this->skill, true);
		$criteria->compare('selected_skill', $this->selected_skill, true);
		$criteria->compare('preferred_datetime', $this->preferred_datetime, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longtitude', $this->longtitude);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('client_attachments', $this->client_attachments, true);
		$criteria->compare('response_datetime', $this->response_datetime, true);
		$criteria->compare('signature', $this->signature, true);
		$criteria->compare('is_agree', $this->is_agree);
		$criteria->compare('status', $this->status);
		$criteria->compare('bid_datetime', $this->bid_datetime, true);
		$criteria->compare('offer_datetime', $this->offer_datetime, true);
		$criteria->compare('offer_status', $this->offer_status);
		$criteria->compare('total_amount', $this->total_amount);
		$criteria->compare('payment_info', $this->payment_info, true);
		$criteria->compare('payment_datetime', $this->payment_datetime, true);
		$criteria->compare('review_by_client', $this->review_by_client);
		$criteria->compare('review_by_user', $this->review_by_user);
		$criteria->compare('temp_review', $this->temp_review, true);
		$criteria->compare('is_temp_payment', $this->is_temp_payment);
		$criteria->compare('temp_payment_request_datetime', $this->temp_payment_request_datetime, true);
		$criteria->compare('notification_id', $this->notification_id);
		$criteria->compare('payment_type', $this->payment_type);
		$criteria->compare('payment_request', $this->payment_request);
		$criteria->compare('payment_request_datetime', $this->payment_request_datetime, true);
		$criteria->compare('cancel_datetime', $this->cancel_datetime, true);
		$criteria->compare('is_offer', $this->is_offer);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}