<?php

/**
 * This is the model base class for the table "cms_pages".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CmsPages".
 *
 * Columns in table "cms_pages" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $page_id
 * @property string $page_name
 * @property string $page_description
 * @property string $image
 * @property string $page_title
 * @property integer $is_active
 *
 */
abstract class BaseCmsPages extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms_pages';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CmsPages|CmsPages', $n);
	}

	public static function representingColumn() {
		return 'page_name';
	}

	public function rules() {
		return array(
			array('page_name, page_description,  page_title', 'required'),
				array('image', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'insert'), //
			array('is_active', 'numerical', 'integerOnly'=>true),
			array('page_name,  page_title', 'length', 'max'=>100),
			array('is_active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('page_id, page_name, page_description, image, page_title, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'page_id' => Yii::t('app', 'Page'),
			'page_name' => Yii::t('app', 'Page Name'),
			'page_description' => Yii::t('app', 'Page Description'),
			'image' => Yii::t('app', 'Image'),
			'page_title' => Yii::t('app', 'Page Title'),
			'is_active' => Yii::t('app', 'Is Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('page_id', $this->page_id);
		$criteria->compare('page_name', $this->page_name, true);
		$criteria->compare('page_description', $this->page_description, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('page_title', $this->page_title, true);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}