<?php

/**
 * This is the model base class for the table "offers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Offers".
 *
 * Columns in table "offers" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $offer_id
 * @property integer $user_id
 * @property integer $offer_by
 * @property string $selected_skill
 * @property string $preferred_datetime
 * @property string $address
 * @property double $latitude
 * @property double $longtitude
 * @property string $notes
 * @property string $client_attachments
 * @property string $response_datetime
 * @property integer $status
 * @property string $offer_datetime
 *
 */
abstract class BaseOffers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'offers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Offers|Offers', $n);
	}

	public static function representingColumn() {
		return 'selected_skill';
	}

	public function rules() {
		return array(
			array('user_id, offer_by, selected_skill, preferred_datetime, address, latitude, longtitude, notes, client_attachments, response_datetime, status, offer_datetime', 'required'),
			array('user_id, offer_by, status', 'numerical', 'integerOnly'=>true),
			array('latitude, longtitude', 'numerical'),
			array('offer_id, user_id, offer_by, selected_skill, preferred_datetime, address, latitude, longtitude, notes, client_attachments, response_datetime, status, offer_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'offer_id' => Yii::t('app', 'Offer'),
			'user_id' => Yii::t('app', 'User'),
			'offer_by' => Yii::t('app', 'Offer By'),
			'selected_skill' => Yii::t('app', 'Selected Skill'),
			'preferred_datetime' => Yii::t('app', 'Preferred Datetime'),
			'address' => Yii::t('app', 'Address'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longtitude' => Yii::t('app', 'Longtitude'),
			'notes' => Yii::t('app', 'Notes'),
			'client_attachments' => Yii::t('app', 'Client Attachments'),
			'response_datetime' => Yii::t('app', 'Response Datetime'),
			'status' => Yii::t('app', 'Status'),
			'offer_datetime' => Yii::t('app', 'Offer Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('offer_id', $this->offer_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('offer_by', $this->offer_by);
		$criteria->compare('selected_skill', $this->selected_skill, true);
		$criteria->compare('preferred_datetime', $this->preferred_datetime, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longtitude', $this->longtitude);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('client_attachments', $this->client_attachments, true);
		$criteria->compare('response_datetime', $this->response_datetime, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('offer_datetime', $this->offer_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}