<?php

/**
 * This is the model base class for the table "user_skill".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSkill".
 *
 * Columns in table "user_skill" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $service_name
 * @property integer $category_id
 * @property integer $subcategory_id
 * @property double $price
 * @property integer $price_type
 * @property string $start_time
 * @property string $end_time
 * @property string $description
 * @property string $service_photo
 * @property integer $is_active
 *
 */
abstract class BaseUserSkill extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_skill';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserSkill|UserSkills', $n);
	}

	public static function representingColumn() {
		return 'service_name';
	}

	public function rules() {
		return array(
			array('user_id, service_name, category_id, subcategory_id, price, price_type, start_time, end_time, description, service_photo', 'required'),
			array('user_id, category_id, subcategory_id, price_type, is_active', 'numerical', 'integerOnly'=>true),
			array('price', 'numerical'),
			array('service_name', 'length', 'max'=>200),
			array('start_time, end_time', 'length', 'max'=>50),
			array('is_active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, service_name, category_id, subcategory_id, price, price_type, start_time, end_time, description, service_photo, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'service_name' => Yii::t('app', 'Service Name'),
			'category_id' => Yii::t('app', 'Category'),
			'subcategory_id' => Yii::t('app', 'Subcategory'),
			'price' => Yii::t('app', 'Price'),
			'price_type' => Yii::t('app', 'Price Type'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'description' => Yii::t('app', 'Description'),
			'service_photo' => Yii::t('app', 'Service Photo'),
			'is_active' => Yii::t('app', 'Is Active'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('service_name', $this->service_name, true);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('subcategory_id', $this->subcategory_id);
		$criteria->compare('price', $this->price);
		$criteria->compare('price_type', $this->price_type);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('service_photo', $this->service_photo, true);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}