<?php

/**
 * This is the model base class for the table "usercard".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usercard".
 *
 * Columns in table "usercard" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $card_id
 * @property integer $user_id
 * @property string $cardtoken
 * @property integer $exp_month
 * @property integer $exp_year
 * @property string $cardnumber
 * @property string $brand
 * @property integer $is_default
 * @property string $created_at
 *
 */
abstract class BaseUsercard extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'usercard';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usercard|Usercards', $n);
	}

	public static function representingColumn() {
		return 'cardtoken';
	}

	public function rules() {
		return array(
			array('user_id, cardtoken, exp_month, exp_year, cardnumber, brand, created_at', 'required'),
			array('user_id, exp_month, exp_year, is_default', 'numerical', 'integerOnly'=>true),
			array('cardtoken, cardnumber', 'length', 'max'=>100),
			array('brand', 'length', 'max'=>50),
			array('is_default', 'default', 'setOnEmpty' => true, 'value' => null),
			array('card_id, user_id, cardtoken, exp_month, exp_year, cardnumber, brand, is_default, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'card_id' => Yii::t('app', 'Card'),
			'user_id' => Yii::t('app', 'User'),
			'cardtoken' => Yii::t('app', 'Cardtoken'),
			'exp_month' => Yii::t('app', 'Exp Month'),
			'exp_year' => Yii::t('app', 'Exp Year'),
			'cardnumber' => Yii::t('app', 'Cardnumber'),
			'brand' => Yii::t('app', 'Brand'),
			'is_default' => Yii::t('app', 'Is Default'),
			'created_at' => Yii::t('app', 'Created At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('card_id', $this->card_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('cardtoken', $this->cardtoken, true);
		$criteria->compare('exp_month', $this->exp_month);
		$criteria->compare('exp_year', $this->exp_year);
		$criteria->compare('cardnumber', $this->cardnumber, true);
		$criteria->compare('brand', $this->brand, true);
		$criteria->compare('is_default', $this->is_default);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}